// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use DIRECT_URL for migrate/db push (Neon non-pooled); app uses DATABASE_URL via adapter in lib/prisma.ts
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
